### ISSUE TITLE
Alternative name for website/repository

### ISSUE THREAD

**Issue by sabu36** [runarberg/random-go-stone-placements#14]
@runarberg I really like the name used in your icelandic website: improv go.

The name of the wikipedia [article](https://en.wikipedia.org/wiki/Go_(game)) for the original game: Go (game).

So for the repository name, how about: improv-go-game?

And for the website: Improv Go, since there's already a descriptive subtitle.

Maybe just for the website? I wonder what you think.

**Comment by runarberg** [comment]
I like it. Improv go generator is objectively a better name :wink:  Let’s keep this issue open and I try to find time sometime in September to change it.

**Comment by runarberg** [comment]
The online-go group is called [*Random Moves Start - Improvisation Go!*](https://online-go.com/group/1557) Other possibilities are [*Fuseki Shuffle*](https://senseis.xmp.net/?FusekiShuffle) or [*Random Start Go*](https://senseis.xmp.net/?RandomStartGo).

**Comment by sabu36** [comment]
On second thought, if we change, it might be better to only change the **title** in `index.html` to leave the possibility of a different name in the future.
* "Improv" sounds more casual and seems to be associated with comedy in particular; "Improvisation" seems more general.

  I personally prefer casual and comedic connotation but, [according](https://en.wikipedia.org/wiki/Fischer_random_chess#Naming) to the person who came up with the name "chess960", the name *should not include negatively biased or "spongy" elements (such as "random" or "freestyle")*. In the comment section of another [article](http://www.chessintranslation.com/2011/06/its-the-end-of-classical-chess-as-we-know-it-and-i-feel-fine/), I also saw a few people finding the name "chess960" boring or clumsy. 

  We don't have a number to use and I don't know a name that satisfies the condition in our case.
* In other games like MTG and Pokemon battling, I saw not insignificant number of people exclusively interested in formats with randomized pools/ingredients. There's a possibility that someone gets interested in Go through this format who otherwise wouldn't be, and a Go-specific terminology like "fuseki" might make it appear uninviting.
* "Random start go" makes it clear that we only change the start of the game. I wish there's also a way to succinctly express that randomization in our case can have structure.

All in all, it seems hard to beat the snappiness of "improv" so far.

**Comment by sabu36** [comment]
A candidate for a new title is "Improv Go: Starting Position Generator" or "ImprovGo Starting Position Generator", basically the current subtitle plus improv-, and randomness is implied.

> Improv go generator is objectively a better name 😉

Alternative, more descriptive option is title: "Improv Go" or "Improv Go Generator", with subtitle: "Generate a starting position for a variant of board game Go".
<hr>

The word "improvised" in the previous candidate "improvised Go" has more general connotation than "improv" and probably easier to translate. However, the standard Go game also has improvisation at some point. The word "improv" in "Improv Go" or "ImprovGo" is used as part of a new name rather than as qualification.

Another reason why I like the word "improv" is that I want to slightly de-emphasize competition and emphasize somewhat collaborative, shape-making aspect of the game for people who might play the game as a [cerebral backdrop](https://en.wikipedia.org/wiki/Furniture_music#Revival), while discussing something else for example.

**Comment by sabu36** [comment]
More I think about it, the current subtitle is actually already solid. I previously thought "random" is implied by "generate" and redundant but it's probably the word people use when searching.

> Improv go generator is objectively a better name 😉 Let’s keep this issue open and I try to find time sometime in September to change it.

It might be better to only change the **title** in `index.html` and keep the repository name for the possibility of another name in the future.

**Comment by sabu36** [comment]
I realized the name hardly matters. Sorry for making an empty request.
